#!/usr/bin/env bash
# generate-dashboard.sh — Renders Phase B promotion dashboard from gate metrics
#
# Usage: bash generate-dashboard.sh /path/to/gates.json
# Output: Writes LOGS/phase-b-dashboard.md

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GATES_FILE="${1:-/dev/stdin}"
DASHBOARD="${REPO_ROOT}/LOGS/phase-b-dashboard.md"
LOGFILE="${REPO_ROOT}/LOGS/agent-runs.jsonl"

# ── Parse gate metrics ─────────────────────────────────────────────
# Simple JSON value extractor (no jq dependency)
jval() { local v; v=$(grep -oE "\"$1\":[^,}]*" "$GATES_FILE" 2>/dev/null | head -1 | cut -d: -f2 | tr -d ' "' || true); echo "${v:-0}"; }

G1=$(jval gate_1_consecutive_publishes)
G1T=$(jval gate_1_target)
G2=$(jval gate_2_violation_free_days)
G2T=$(jval gate_2_target)
G3R=$(jval gate_3_pass_rate)
G3N=$(jval gate_3_total_runs)
G3TR=$(jval gate_3_target_rate)
G3TN=$(jval gate_3_target_runs)
G4=$(jval gate_4_drill_completed)
G5P=$(jval gate_5_coverage_pct)
G5L=$(jval gate_5_logged_today)
G5E=$(jval gate_5_expected_daily)
TOTAL=$(jval total_log_entries)
COMPUTED=$(jval computed_at)

# ── Status emoji logic ────────────────────────────────────────────
status_emoji() {
  local current="$1" target="$2"
  local pct=$((current * 100 / (target > 0 ? target : 1)))
  if [[ $pct -ge 100 ]]; then echo "✅"
  elif [[ $pct -ge 50 ]]; then echo "🟡"
  else echo "🔴"
  fi
}

pct() {
  local current="$1" target="$2"
  if [[ $target -gt 0 ]]; then
    echo "$((current * 100 / target))%"
  else
    echo "0%"
  fi
}

E1=$(status_emoji "$G1" "$G1T")
E2=$(status_emoji "$G2" "$G2T")
# Gate 3 needs both pass rate AND sample size
if [[ $G3N -ge $G3TN && $G3R -ge $G3TR ]]; then E3="✅"
elif [[ $G3N -ge 25 || $G3R -ge 90 ]]; then E3="🟡"
else E3="🔴"
fi
# Gate 4
if [[ "$G4" == "true" ]]; then E4="✅"; else E4="🔴"; fi
# Gate 5
E5=$(status_emoji "$G5P" 100)

# Count gates passed
PASSED=0
[[ $G1 -ge $G1T ]] && PASSED=$((PASSED + 1))
[[ $G2 -ge $G2T ]] && PASSED=$((PASSED + 1))
[[ $G3N -ge $G3TN && $G3R -ge $G3TR ]] && PASSED=$((PASSED + 1))
[[ "$G4" == "true" ]] && PASSED=$((PASSED + 1))
[[ $G5P -ge 100 ]] && PASSED=$((PASSED + 1))

# ── Generate 7-day trend ──────────────────────────────────────────
TREND=""
if [[ -f "$LOGFILE" && -s "$LOGFILE" ]]; then
  for i in 0 1 2 3 4 5 6; do
    if date -v-1d +%Y-%m-%d &>/dev/null 2>&1; then
      D=$(date -u -v-${i}d +"%Y-%m-%d")
    else
      D=$(date -u -d "${i} days ago" +"%Y-%m-%d")
    fi
    DAY_ENTRIES=$(grep "\"${D}" "$LOGFILE" 2>/dev/null || true)
    if [[ -n "$DAY_ENTRIES" ]]; then
      DAY_TOTAL=$(echo "$DAY_ENTRIES" | (grep '"action_type":"cron_run"' || true) | wc -l | xargs)
      DAY_PASS=$(echo "$DAY_ENTRIES" | (grep '"action_type":"cron_run"' || true) | (grep '"outcome":"pass"' || true) | wc -l | xargs)
      DAY_FAIL=$((DAY_TOTAL - DAY_PASS))
      DAY_VIOL=$(echo "$DAY_ENTRIES" | (grep '"outcome":"violation_red"' || true) | wc -l | xargs)
      TREND+="| ${D} | ${DAY_TOTAL} | ${DAY_PASS} | ${DAY_FAIL} | ${DAY_VIOL} |
"
    fi
  done
fi

# ── Write dashboard ───────────────────────────────────────────────
cat > "$DASHBOARD" <<EOF
# 📊 Phase B Promotion Dashboard

> Auto-generated by \`phase-b-tracker\` · ${COMPUTED}
> Reference: [phase-a-to-b.md](../POLICIES/phase-a-to-b.md)

## Gate Status

| Gate | Requirement | Current | Target | Status |
|------|-------------|---------|--------|--------|
| §1 Consecutive publishes | ≥${G1T} clean in 30 days | **${G1}** | ${G1T} | ${E1} $(pct "$G1" "$G1T") |
| §2 Zero red violations | ${G2T} contiguous days | **${G2} days** | ${G2T} | ${E2} $(pct "$G2" "$G2T") |
| §3 Quality gate pass rate | ≥${G3TR}% over ${G3TN} runs | **${G3R}%** (${G3N} runs) | ${G3TR}% / ${G3TN} runs | ${E3} |
| §4 Incident drill | 1 completed | **$([ "$G4" == "true" ] && echo "Done" || echo "Not done")** | 1 | ${E4} |
| §5 Logging coverage | 100% structured | **${G5P}%** (${G5L}/${G5E} today) | 100% | ${E5} |

**Overall: ${PASSED}/5 gates passed**

---

## 7-Day Trend

| Date | Runs | Passed | Failed | Red Violations |
|------|------|--------|--------|----------------|
$(printf '%s' "$TREND")

---

## Metrics

| Metric | Value |
|--------|-------|
| Total log entries | ${TOTAL} |
| Log file | \`LOGS/agent-runs.jsonl\` |
| Last computed | ${COMPUTED} |

---

*This file is auto-generated. Do not edit manually.*
EOF

echo "✅ Dashboard written to LOGS/phase-b-dashboard.md"
